// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.iOS.Support.XamarinSidebarSample.iOS.Views;
using UIKit;

namespace MvvmCross.iOS.Support.XamarinSidebarSample.iOS
{
	//public partial class TalentPoolViewController : BaseMvxViewController<ShiftTemplatesViewModel>
	//{
	//	public TalentPoolViewController (IntPtr handle) : base (handle)
	//	{
	//	}
	//}
}
